### ISSUE TITLE
Keep showing snackBar

### ISSUE THREAD

**Issue by tenSunFree** [bachhoan88/CleanArchitecture#22]
**Is your feature request related to a problem? Please describe.**
Turn off the mobile network first, and then click search on the main screen. At this time, snackBar will be shown
Then open the mobile phone network, then click search on the main screen to jump to the contributor  screen, and then press the return key to jump back to the main screen, this time will automatically show snackBar 
![Screenshot_20200314-232714](https://user-images.githubusercontent.com/23090085/76685462-c2ce3e80-664e-11ea-942f-a302c0336d19.png)

**Describe the solution you'd like**
Same as above

**Describe alternatives you've considered**
The picture below is my solution, maybe you can refer to it
![2020-03-14_233106](https://user-images.githubusercontent.com/23090085/76685497-2e181080-664f-11ea-99d8-355d6c7142bb.jpg)
![2020-03-14_234559](https://user-images.githubusercontent.com/23090085/76685499-32442e00-664f-11ea-9848-17b839a94a7f.jpg)

**Comment by bachhoan88** [comment]
Thanks 
I've fixed on #25
